// <auto-generated />
using System;
using ClashVillagePulse.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClashVillagePulse.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321172900_AddPrioritySuggestionRankAndHallCaps")]
    partial class AddPrioritySuggestionRankAndHallCaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.Clan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClanTag")
                        .IsUnique();

                    b.ToTable("clans", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.ClanMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId", "UserId")
                        .IsUnique();

                    b.ToTable("clan_members", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.ClanPriorityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BuilderHallLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<int?>("TownHallLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClanId", "Section", "TownHallLevel", "BuilderHallLevel", "ItemType", "ItemDataId")
                        .IsUnique();

                    b.ToTable("clan_priority_items", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.LocalizationText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Tid", "LanguageCode")
                        .IsUnique();

                    b.ToTable("localization_texts", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.PrioritySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuggestedPriorityRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId", "Status", "CreatedAtUtc");

                    b.HasIndex("VillageId", "Section", "ItemType", "ItemDataId");

                    b.ToTable("priority_suggestions", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticDataRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("static_data_runs", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticDataRunStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StaticDataRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StaticDataRunId", "TargetKey", "StepType")
                        .IsUnique();

                    b.ToTable("static_data_run_steps", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticHallItemCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HallLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Section", "HallLevel", "ItemType", "ItemDataId")
                        .IsUnique();

                    b.ToTable("static_hall_item_caps", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUpgradeable")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemDataId", "ItemType", "Section")
                        .IsUnique();

                    b.ToTable("static_items", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaticItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UpgradeTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StaticItemId", "Level")
                        .IsUnique();

                    b.ToTable("static_item_levels", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemLevelUpgradeCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaticItemLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaticItemLevelId", "ResourceType")
                        .IsUnique();

                    b.ToTable("static_item_level_upgrade_costs", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("RequiredItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RequirementType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaticItemLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaticItemLevelId", "RequirementType", "RequiredItemDataId", "RequiredLevel");

                    b.ToTable("static_item_requirements", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BuilderHallLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClanName")
                        .HasColumnType("text");

                    b.Property<string>("ClanTag")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastGameTimestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TownHallLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerTag")
                        .IsUnique();

                    b.ToTable("villages", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.VillageItemLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("HelperCooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("HelperTimerSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExtra")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGearUp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHelperRecurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<int?>("SuperchargeLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpgradeTimerSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId", "Section", "ItemType", "ItemDataId", "Level");

                    b.ToTable("village_item_levels", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.VillagePriorityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemDataId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId", "Section", "ItemType", "ItemDataId")
                        .IsUnique();

                    b.ToTable("village_priority_items", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.ClanMember", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Clan", "Clan")
                        .WithMany("Members")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.ClanPriorityItem", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Clan", "Clan")
                        .WithMany("PriorityItems")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.PrioritySuggestion", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Village", "Village")
                        .WithMany("Suggestions")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticDataRunStep", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.StaticDataRun", "StaticDataRun")
                        .WithMany("Steps")
                        .HasForeignKey("StaticDataRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticDataRun");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemLevel", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.StaticItem", "StaticItem")
                        .WithMany("Levels")
                        .HasForeignKey("StaticItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticItem");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemLevelUpgradeCost", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.StaticItemLevel", "StaticItemLevel")
                        .WithMany("UpgradeCosts")
                        .HasForeignKey("StaticItemLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticItemLevel");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemRequirement", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.StaticItemLevel", "StaticItemLevel")
                        .WithMany("Requirements")
                        .HasForeignKey("StaticItemLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticItemLevel");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.Village", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Clan", "Clan")
                        .WithMany("Villages")
                        .HasForeignKey("ClanId");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.VillageItemLevel", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Village", "Village")
                        .WithMany("ItemLevels")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.VillagePriorityItem", b =>
                {
                    b.HasOne("ClashVillagePulse.Domain.Entities.Village", "Village")
                        .WithMany("PriorityItems")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.Clan", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PriorityItems");

                    b.Navigation("Villages");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticDataRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItem", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.StaticItemLevel", b =>
                {
                    b.Navigation("Requirements");

                    b.Navigation("UpgradeCosts");
                });

            modelBuilder.Entity("ClashVillagePulse.Domain.Entities.Village", b =>
                {
                    b.Navigation("ItemLevels");

                    b.Navigation("PriorityItems");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
